//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Nullable<int> ApplicationId { get; set; }
        public int Memberid { get; set; }
    }
}
